
name: simple-lens
version: 0.0.1.0
ghc-options: -Wall -Werror -Wno-unused-matches

dependencies: 
  - base

library:
  source-dirs: src
  exposed-modules:
    - Lib

executables:
  simple-lens-exe:
    source-dirs: app
    main: Main.hs 
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies: simple-lens

tests:
  simple-lens-test:
    source-dirs: test
    main: Spec.hs
    dependencies: 
      - simple-lens
      - QuickCheck
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

